apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: photomanager
  name: photomanager
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photomanager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: photomanager
    spec:
      containers:
        - name: photomanager
          image: registry.structura.dev/photomanager
          env:
            - name: MEDIA_ROOT
              value: /srv/familyphotos/photos
            - name: PUBLIC_URL
              value: http://k3svc3.lan:8998
          ports:
            - containerPort: 8998
              name: webserver
          volumeMounts:
            - mountPath: /srv/familyphotos/photos
              name: familyphotos-localstorage-pvc
            # subPath: photos
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8998
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8998
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: familyphotos-localstorage-pvc
          persistentVolumeClaim:
            claimName: familyphotos-localstorage-pvc
      nodeSelector:
        jellyfin-media-data: "true"
