apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-localstorage-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 1024Gi  # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/datahdd-0/pv/photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: jellyfin-media-data
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: familyphotos-localstorage-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1024Gi  # Adjust size to match PV
