apiVersion: v1
kind: Service
metadata:
  name: photomanager
  namespace: jellyfin
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - name: "webserver"
      port: 8998
      targetPort: 8998
  selector:
    app: photomanager
